[package]
name = "prompt_editline"
version = "0.1.0"
authors = ["a.hildenbrand <a.hildenbrand@gmail.com>"]

[dependencies]
readline = { git = "https://github.com/shaleh/rust-readline" }

#[dependencies]
#editline = { git = "https://github.com/wkz/rust-editline.git" }

